### ISSUE TITLE
[Frontend] Tela de Relatório de Aluno

### ISSUE THREAD

**Issue by GabrielPen1do** [ICEI-PUC-Minas-PMV-ADS/psg-ads-n-tiam-2024-2-gerenciador-escolar#70]
**Criar uma tela que exibe o relatório de desempenho escolar do aluno (notas, presença, e comentários). Incluir o botão "Baixar PDF".**

**Tarefas:**

- Desenvolver o layout do relatório escolar do aluno.
- Adicionar botão "Baixar".
- Configurar a chamada para o endpoint que gera e retorna o PDF.
- Integrar a exibição dos dados do relatório usando a API de relatórios.

**Critérios de aceitação:**

- [ ] A tela deve exibir corretamente as informações do relatório do aluno.
- [ ] O botão "Baixar" deve acionar a requisição para o endpoint e fazer o download do arquivo.
- [ ] Mensagens de erro devem ser exibidas caso o download falhe.

![Image](https://github.com/user-attachments/assets/30521eaf-289b-4335-aedb-b79173594773)
