### ISSUE TITLE
[Backend] Endpoint para Listar Alunos

### ISSUE THREAD

**Issue by GabrielPen1do** [ICEI-PUC-Minas-PMV-ADS/psg-ads-n-tiam-2024-2-gerenciador-escolar#72]
**Criar um endpoint que retorne o relatório escolar de um aluno específico em formato JSON e permita gerar um PDF para download.**

**Tarefas:**

- Criar método no controller para retornar os dados do relatório escolar.
- Implementar funcionalidade para gerar o PDF com os dados do aluno.
- Configurar o retorno do PDF como um arquivo para download.

**Critérios** de Aceitação:

- [ ] Retornar relatório do aluno no formato JSON para exibição no front-end.
- [ ] Permitir a geração e download do PDF ao receber uma requisição.
- [ ] Retornar erros apropriados (403, 404, 500).
