### ISSUE TITLE
[Backend] Endpoint para Lançamento de Notas

### ISSUE THREAD

**Issue by GabrielPen1do** [ICEI-PUC-Minas-PMV-ADS/psg-ads-n-tiam-2024-2-gerenciador-escolar#73]
**Criar** um endpoint que permita lançar ou editar notas de um aluno em uma disciplina específica.

**Tarefas:**

- Criar método no controller para salvar as notas no banco de dados.
- Implementar validações (ex.: verificar se a nota está no intervalo permitido).
- Retornar mensagem de sucesso ou erros apropriados.

**Critérios de Aceitação:**

- [ ] Aceitar dados no formato JSON: aluno, disciplina, nota e comentário.
- [ ] Salvar os dados corretamente no banco de dados.
- [ ] Retornar erros apropriados (400, 403, 500).
