### ISSUE TITLE
Epic: Implementação do sistema de autenticação dos usuários

### ISSUE THREAD

**Issue by GabrielPen1do** [ICEI-PUC-Minas-PMV-ADS/psg-ads-n-tiam-2024-2-gerenciador-escolar#8]
Esta epic inclui as seguintes tarefas:

**Backend:**

- [x] Configurar Firebase Authentication
- [x] Configurar Cadastro de Usuários.
- [x] Autenticação por E-mail e Senha.
- [x] Implementar Recuperação de Senha.
- [x] Persistência de Sessão de Usuário.
- [x] Implementar Logout de Usuários.

**Frontend:**

- [x] Configuração Inicial do Firebase no Projeto React Native.
- [x] Tela de Login com Validação de Formulário.
- [x] Integração com Firebase Authentication (Login com E-mail e Senha).
- [x] Tela de Cadastro de Usuário.
- [x] Persistência de Sessão (Manter o Usuário Logado).
- [x] Logout do Usuário
